### ISSUE TITLE
Need to get all of the CDMX logo work into this repo

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/Design#2]
Let's put it into `CitySpecific/CDMX`

Update: I just invited `gari01234` to this repo, so perhaps he can add the CDMX logo work directly. If not, he can send it to me and I'll add it.

**Comment by gari01234** [comment]
:white_check_mark: 
Please let me know if something is missing. I will continue adding the content that is made.

**Comment by jonfroehlich** [comment]
Love it! They are all so creative and professionally done. One of my favs:

![image](https://user-images.githubusercontent.com/1621749/90402655-9e8ae980-e054-11ea-9ed9-920052117546.png)
