### ISSUE TITLE
When I tried opening "mission icons raw.ai" got an error

### ISSUE THREAD

**Issue by jonfroehlich** [ProjectSidewalk/Design#4]
![image](https://user-images.githubusercontent.com/1621749/190519666-75fdb62f-5450-45c8-87ec-8f951318a2d8.png)

It's actually missing three files:
- "color palette.png" <-- this one is in the repo `\Mocks\DuanhaosLabelingRedesign`
- "Final - Mockup with new icons & colors 2.png"
- "Final - Mockup with new icons & colors 3.png"

**Comment by Luciozzz** [comment]
The missing files are screen mockups. This is what the complete file looks like:


![image](https://user-images.githubusercontent.com/18668038/190526382-a2503d02-adb4-4cb3-b264-170fc8651952.png)

**Comment by Luciozzz** [comment]
I'll also post the missing files here in case we need it:
![Final - Mockup with new icons   colors 2](https://user-images.githubusercontent.com/18668038/190526470-5d3fb631-fc9a-4540-8f84-ab86e1313162.png)
![Final - Mockup with new icons   colors 3](https://user-images.githubusercontent.com/18668038/190526475-9e8c57c5-fc3b-4a97-83fb-fcded45ba071.png)

**Comment by jonfroehlich** [comment]
Awesome fixed!

![image](https://user-images.githubusercontent.com/1621749/190542883-46bfeed5-d13c-46b0-8205-44ebfce06936.png)
